name: enmay_flutter_starter
description: "Flutter Starter Template"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  reactive_forms: ^17.0.1
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.0.17
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/animations/
    - assets/animations/lottie/
    - assets/data/json/
